services:
  primary:
    image: postgres:16
    container_name: pg_primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: primary_pass
    ports:
      - "5433:5432"
    volumes:
      - primary-data:/var/lib/postgresql/data
      - ./init/primary-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init/primary-config.sh:/docker-entrypoint-initdb.d/2-config.sh
    networks:
      - pgnet

  shard:
    image: postgres:16
    container_name: pg_shard
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shard_pass
    ports:
      - "5435:5432"
    volumes:
      - shard-data:/var/lib/postgresql/data
      - ./init/shard-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pgnet

  replica:
    build:
      context: .
      dockerfile: Dockerfile.replica
    container_name: pg_replica
    environment:
      REPLICA_USER: replicator
      REPLICA_PASSWORD: replica_pass
      PRIMARY_HOST: primary
      PRIMARY_PORT: 5432
    depends_on:
      - primary
    ports:
      - "5434:5432"
    volumes:
      - replica-data:/var/lib/postgresql/data
      - ./setup-replica.sh:/docker-entrypoint-initdb.d/setup-replica.sh
    networks:
      - pgnet

volumes:
  primary-data:
  shard-data:
  replica-data:

networks:
  pgnet:
